services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
