[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
axum = "0.8.4"
sea-orm = { version = "1.1.13", features = [ "sqlx-postgres", "tokio", "macros" ] }
